#!/bin/sh
apt-get update
sudo apt-get install qt5-default
sudo apt-get install libqt5webkit5-dev
sudo apt-get install libqt5xmlpatterns5-dev
sudo apt-get install libssl-dev
sudo apt-get install libsecret-1-dev
sudo apt-get install freeglut3-dev
sudo apt-get install git
cd ~
git clone https://github.com/AzureAD/rms-sdk-for-cpp
cd rms-sdk-for-cpp
cd sdk
qmake
make
cd ../samples
qmake
make
cd ../bin
export LD_LIBRARY_PATH=`pwd`
cd ../scripts
./build_and_test.sh
